spark.master                                  spark://spark-master:7077
spark.app.name                                payments-raw-accounts
spark.eventLog.enabled                        true
spark.eventLog.dir                            file:///tmp/spark-events
spark.history.fs.logDirectory                 file:///tmp/spark-events

spark.sql.session.timeZone                    UTC
spark.sql.shuffle.partitions                  8
spark.default.parallelism                     8
spark.serializer                              org.apache.spark.serializer.KryoSerializer

spark.hadoop.fs.s3a.impl                      org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider  com.amazonaws.auth.EnvironmentVariableCredentialsProvider
spark.hadoop.fs.s3a.path.style.access         false
spark.hadoop.fs.s3a.fast.upload               true
spark.hadoop.fs.s3a.connection.ssl.enabled    true

spark.sql.sources.partitionOverwriteMode      dynamic
